### ISSUE TITLE
Invalid Course - No Notification

### ISSUE THREAD

**Issue by vogtl19** [upcs/cs-341-project-sq19-golf#28]
Recreate: 
1. Type in CS
2. Type in an invalid course number like 999
3. Submit
4. Generates blank schedule, does not notify the user that there is an invalid course and they have to start over. The user does not know which course is invalid if multiple classes are entered.

**Comment by Quach19** [comment]
Thank you for the suggestion! This is something we haven't thought of, but we should definitely implement.

**Comment by Katacka** [comment]
A notification has been added to handle this case
