### ISSUE TITLE
Autofill suggestion doesn't go away

### ISSUE THREAD

**Issue by ashika-m** [upcs/cs-341-project-sq19-golf#30]
The autofill course suggestion doesn't change when the user is done typing.
1. Started typing CS
2. CST was the suggested autofill
3. The autofill didn't go away when I finished typing

**Comment by Quach19** [comment]
This is something we are looking into. Thank you for pointing it out to us.

**Comment by Katacka** [comment]
Due to the nature of the our inline-autofill this cannot be fixed as currently setup. Due to the low overall impact (it only affects CS to CST), this feature will not be implemented. This would be an extension of high priority if more time was allowed.
