### ISSUE TITLE
Entering in a Semester - Invalid Semester Number

### ISSUE THREAD

**Issue by schibel21** [upcs/cs-341-project-sq19-golf#31]
When I enter in an invalid semester it does not give a notification that it is not a valid semester and it generates the one for Fall of 2019 anyway. 

1.) Clicked on "Select Courses For" text box
2.) Changed course semester to something invalid: "Fall 209"
3.) Entered in course names and numbers
4.) Submitted and still generated the Fall of 2019 schedule with an invalid semester number

**Comment by Katacka** [comment]
This thread has been closed as a duplicate. Please see https://github.com/upcs/cs-341-project-sq19-golf/issues/34#issue-431580079 for a resolution
