### ISSUE TITLE
Semester Input

### ISSUE THREAD

**Issue by chrisfishback** [upcs/cs-341-project-sq19-golf#34]
Instead of having a text input for the semester, you could use something like a dropdown menu, that way only available semesters and their classes could be used.

**Comment by Katacka** [comment]
That is certainly on our list of things to do! Thank you for the note

**Comment by Katacka** [comment]
Recognizing that a history of past courses is not useful for scheduling (and a feature which works quite acceptably with Self Serve), the semester/year input has been modified to not display input - instead serving to communicate the contextual data available
